In [3]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
%pylab inline
from sklearn import (cluster,datasets)
from scipy import misc
k_means = cluster.KMeans(n_clusters=10, n_init=4)
iris = datasets.load_iris()
iris.target

Populating the interactive namespace from numpy and matplotlib


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
from sklearn import datasets
from sklearn.mixture import GaussianMixture

import numpy as np
iris = datasets.load_iris()
estimator = GaussianMixture(n_components=10,covariance_type='full')
estimator.fit(iris.data)

#hard clustering
#estimator.predict(iris.data)
#estimator.covariances_

#Soft clustering
estimator.predict_proba(iris.data)


array([[  1.96798425e-003,   4.35434854e-064,   2.33897238e-036, ...,
          0.00000000e+000,   8.78318478e-002,   7.36909454e-139],
       [  9.92845708e-001,   2.59995408e-046,   3.09550105e-025, ...,
          0.00000000e+000,   6.64787186e-003,   3.19509872e-140],
       [  9.99012209e-001,   1.86881332e-063,   1.41896050e-031, ...,
          0.00000000e+000,   5.00491121e-004,   4.36273320e-147],
       ..., 
       [  0.00000000e+000,   8.30200640e-007,   5.08039248e-007, ...,
          0.00000000e+000,   8.37389405e-173,   3.96683909e-003],
       [  0.00000000e+000,   5.32827128e-034,   2.78437942e-007, ...,
          0.00000000e+000,   1.21733110e-182,   9.97299766e-001],
       [  0.00000000e+000,   4.55056691e-032,   3.45106777e-002, ...,
          0.00000000e+000,   4.86923582e-140,   4.00033099e-014]])

In [13]:
#N on-parametric Gaussian mixtures
from sklearn import datasets
#from sklearn.mixture import GaussianMixture
from sklearn.mixture import BayesianGaussianMixture
import numpy as np
iris = datasets.load_iris()
estimator = BayesianGaussianMixture(n_components=25)
estimator.fit(iris.data)
#estimator.weights_

array([  1.08486301e-01,   3.35147526e-01,   6.52411158e-03,
         6.44759912e-03,   6.37198425e-03,   6.29725645e-03,
         1.26873489e-01,   1.88656138e-02,   6.03289270e-03,
         3.78716647e-01,   2.27479575e-04,   8.74921442e-06,
         3.36508247e-07,   1.29426249e-08,   4.97793265e-10,
         1.91458948e-11,   7.36380569e-13,   2.83223296e-14,
         1.08932037e-15,   4.18969373e-17,   1.61142066e-18,
         6.19777178e-20,   2.38375838e-21,   9.16830146e-23,
         3.52626979e-24])